language: python
cache: pip
dist: xenial
sudo: required
git:
  depth: 1

notifications:
  email: false

python:
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install pytest lxml
  - pip install -e .

script:
  - pytest
