language: python
cache: pip
git:
  depth: 1

notifications:
  email: false


python:
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install pipenv --upgrade
  - pipenv install --skip-lock

script:
  - pipenv run pytest
