language: python
cache: pip
git:
  depth: 1

notifications:
  email: false


python:
   - 3.5
   - 3.6
   - nightly

install:
   - pip install pytest-xdist pytest lxml --upgrade

script:
   - python setup.py test
