language: python
cache: pip
git:
  depth: 1

notifications:
  email: false


python:
   - 3.5
   - 3.6
   - nightly
   - pypy3

install:
   - pip install pytest-xdist pytest wheel --upgrade

script:
   - python setup.py test
